export const SET_USER = "SET_USER"
export const SET_DATA = "SET_DATA"
export const SET_MTYPE = "SET_MTYPE"
export const SET_LAMBDA = "SET_LAMBDA"
export const SET_MLIST = "SET_MLIST"

export const SET_LAYER = "SET_LAYER"
export const SET_LAYERLIST = "SET_LAYERLIST"
export const SET_UPDATEU = "SET_UPDATEU"
export const SET_MATERIAL = "SET_MATERIAL"
export const SET_DELETE = "SET_DELETE"
export const SET_COLOR = "SET_COLOR"
export const SET_VIEW = "SET_VIEW"
export const SET_COLORNAVBAR = "SET_COLORNAVBAR"
export const SET_TOTALU = "SET_TOTALU"
export const SET_RECALCU = "SET_RECALCU"
export const SET_PRICE = "SET_PRICE"
export const SET_TOTALPRICE = "SET_TOTALPRICE"